import type {Metadata} from 'next';
import Image from 'next/image';
import {InteriorHero} from '@/components/InteriorHero';

export const metadata:Metadata={title:'Как начинается мебельный проект',description:'Шесть этапов, которые сайт может показать реальному производителю мебели на заказ.',alternates:{canonical:'/about/'}};

const steps=[['Разговор о задаче','Комната, привычки, ограничения и то, что сейчас мешает в хранении.'],['Замер пространства','Геометрия стен, углы, выводы, открывания и реальные проходы.'],['Планировка и хранение','Объёмы, ежедневные маршруты, техника и доступ к вещам.'],['Материалы','Фасады, корпуса, профили, стекло и поверхности проверяются при реальном свете.'],['Согласование','Чертёж, комплектация, материалы и привязки собираются в один понятный документ.'],['Изготовление и монтаж','Для реального производителя сайт может показать этот этап после подключения его сроков, гарантий и процессов.']];
const stepImages=['/images/room-office-warm.jpg','/images/workshop.jpg','/images/room-living-detail.jpg','/images/editorial-12.jpg','/images/room-bedroom-wood.jpg','/images/editorial-11.jpg'];

export default function About(){return <div className="page immersivePage aboutPage"><InteriorHero image="/images/room-office-warm.jpg" alt="Тёплая рабочая зона, встроенная в интерьер" eyebrow="Как начинается индивидуальный проект" title="Сначала пространство. Потом мебель." lead="Одна последовательность работает для кухни, гардеробной, гостиной и рабочего места: задача, точная геометрия, хранение и только затем материал." note="06 понятных этапов" position="center 52%"/><section className="aboutOpening section"><figure><Image src="/images/workshop.jpg" alt="Рабочий стол с образцами древесины" fill sizes="(max-width: 800px) 100vw, 48vw"/></figure><div><p className="eyebrow">Структура вместо обещаний</p><h2>Процесс должен быть виден так же ясно, как готовый интерьер</h2><p>Эта демонстрация не придумывает производство, сроки или гарантии. Она показывает, как реальный мебельный бренд может спокойно объяснить путь от первого разговора до монтажа.</p><ol className="processIndex" aria-label="Логика работы"><li>01 Разговор</li><li>02 Замер</li><li>03 Планировка</li><li>04 Материалы</li><li>05 Согласование</li><li>06 Монтаж</li></ol></div></section><section className="processChapters">{steps.map(([title,text],index)=><article className="processChapter" key={title}><figure><Image src={stepImages[index]} alt="Интерьерный и рабочий референс этапа проекта" fill sizes="(max-width: 800px) 100vw, 55vw"/></figure><div><span>{String(index+1).padStart(2,'0')}</span><p className="eyebrow">Этап проекта</p><h2>{title}</h2><p>{text}</p></div></article>)}</section><section className="aboutDemoNote section"><p className="eyebrow">О демонстрационной версии</p><h2>Здесь нет вымышленных заказчиков и производственных обещаний</h2><p>«СЛОЙ 52» — вымышленный бренд и портфолио разработчика. Реальному производителю понадобятся собственные проекты, сроки, гарантии, контакты и процессы. Кухонный расчёт здесь служит только для проверки интерфейса.</p></section></div>}
