import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {projects,layoutNames} from '@/data/projects';
import {Compare} from '@/components/Compare';
import {KitchenDiagram} from '@/components/KitchenDiagram';
import {defaults} from '@/lib/configurator';
import {facades,countertops} from '@/data/materials';

export const metadata:Metadata={title:'Кухни на заказ — демонстрационный сайт',description:'Современный демонстрационный концепт интерфейса для производителя кухонь на заказ.',alternates:{canonical:'/'}};

export default function Home(){return <>
  <section className="hero"><div className="heroCopy"><p className="eyebrow">Демонстрационный интерфейс</p><h1>Кухня, в которой всё на своём месте</h1><p className="lead">Собираем проект вокруг размеров комнаты, техники и привычек семьи. Сначала можно посмотреть концепты и прикинуть бюджет самостоятельно.</p><div className="heroActions"><Link className="button" href="/calculator">Прикинуть бюджет</Link><Link className="textButton" href="/projects">Смотреть проекты</Link></div><p className="demoLine">Демонстрационный концепт сайта производителя кухонь на заказ</p></div><div className="heroImage"><Image src="/images/editorial-11.jpg" alt="Тёмная кухня с цельным объёмом хранения" fill loading="eager" fetchPriority="high" sizes="(max-width: 800px) 100vw, 58vw"/><span>01 / хранение и рабочая линия</span></div></section>
  <section className="section featured"><div className="sectionHead"><p className="eyebrow">Каталог компоновок</p><h2>Концепты для разных комнат</h2><p>Шесть вариантов показывают, как меняются планировка, хранение и характер материалов.</p></div><div className="featuredGrid">{projects.slice(0,4).map((project,index)=><Link className={`feature f${index}`} href={`/projects/${project.slug}`} key={project.slug}><div><Image src={project.image} alt={project.alt} fill sizes="(max-width: 700px) 100vw, 50vw"/></div><p><span>концепт · {layoutNames[project.layout]}</span><b>{project.name}</b><small>{project.room} · {project.facade}<br/>{project.top}<br/>{project.task}</small></p></Link>)}</div></section>
  <Compare/>
  <section className="section materialStrip"><div className="sectionHead"><p className="eyebrow">Поверхности крупным планом</p><h2>Материал задаёт ритм</h2><p>Фасад можно поменять. Неудобную высоту столешницы — уже сложнее.</p></div><p className="railHint">Листайте образцы в сторону →</p><div className="texturesRail">{[...facades,...countertops].map(material=><article key={material.id}><i className={`texture ${material.texture}`}/><h3>{material.name}</h3><p>{material.note}</p></article>)}</div><Link className="textButton" href="/materials">Разобраться в материалах</Link></section>
  <section className="section process"><div className="processIntro"><p className="eyebrow">Последовательная работа</p><h2>Сначала комната, потом фасад</h2><Image src="/images/workshop.jpg" alt="Рабочий стол с образцами дерева" width={700} height={900}/></div><ol>{[['01','Разговор','Фиксируем привычки, технику и то, что мешает в нынешней кухне.'],['02','Замер','Проверяем геометрию, выводы и ограничения комнаты.'],['03','Планировка','Распределяем рабочие зоны и хранение.'],['04','Выбор материалов','Сопоставляем тактильность, уход и условный бюджет.'],['05','Изготовление','После согласования чертежей комплект деталей переходит в работу.'],['06','Монтаж','На месте собирают модули и проверяют стыки, фасады и технику.']].map(([number,title,text])=><li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><Image className="processImage" src="/images/editorial-12.jpg" alt="Светлый шпон и рабочая зона у мойки" width={900} height={1200}/></section>
  <section className="calCta"><div><p className="eyebrow">Предварительный диапазон</p><h2>Соберите черновик кухни</h2><p>Выберите форму, размеры и материалы. Расчёт нужен для первого разговора и не подменяет замер или проект.</p><Link className="button" href="/calculator">Собрать черновик кухни</Link></div><KitchenDiagram config={defaults}/></section>
  <section className="finalCta"><p className="eyebrow">Следующий шаг</p><h2>Есть размеры комнаты? Начнём с них.</h2><p>Соберите черновик — планировка и материалы останутся рядом с обращением.</p><div className="heroActions"><Link className="button" href="/calculator">Собрать черновик</Link><Link className="textButton" href="/contacts">Обсудить проект</Link></div></section>
</>}
