'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {calculate,defaults,dimensionSummary,KitchenConfig,Layout,OptionId,restore,selectedOptionLabels,serialize,validateDimensions,type ZoneId,type WallId} from '@/lib/configurator';
import {availableWalls,defaultZones,normalizeZones} from '@/lib/kitchen-model';
import {facades,countertops,FacadeId,TopId,handles} from '@/data/materials';
import {KitchenDiagram} from './KitchenDiagram';
import {KitchenFront} from './KitchenFront';

const layouts:{id:Layout;name:string}[]=[{id:'straight',name:'Прямая'},{id:'corner',name:'Угловая'},{id:'u',name:'П-образная'},{id:'island',name:'С островом'}];
const steps=['Форма и размеры','Расположение зон','Материалы','Оснащение','Черновик расчёта'];
const zones:{id:ZoneId;name:string;note:string}[]=[{id:'fridge',name:'Холодильник',note:'Высокий модуль или край рабочей линии.'},{id:'sink',name:'Мойка',note:'Модуль с мойкой на выбранной стене.'},{id:'cooktop',name:'Варочная поверхность',note:'Модуль с варочной поверхностью.'}];
const optionList:{id:OptionId;name:string;note:string;service?:boolean}[]=[{id:'uppers',name:'Верхние шкафы',note:'Хранение над рабочей поверхностью.'},{id:'columns',name:'Колонны под технику',note:'Высокие модули для техники и хранения.'},{id:'island',name:'Остров',note:'Доступно только для планировки с островом.'},{id:'lights',name:'Подсветка',note:'Световая линия под верхними шкафами.'},{id:'drawers',name:'Организация ящиков',note:'Условное деление нижних модулей.'},{id:'delivery',name:'Доставка',note:'Сервис, не меняет геометрию.',service:true},{id:'installation',name:'Монтаж',note:'Сервис, не меняет геометрию.',service:true}];

export function Configurator(){
  const [ready,setReady]=useState(false),[step,setStep]=useState(1),[config,setConfig]=useState<KitchenConfig>(defaults),[message,setMessage]=useState(''),[view,setView]=useState<'plan'|'front'>('plan'),[activeWall,setActiveWall]=useState<WallId>('a'),[selectedZone,setSelectedZone]=useState<ZoneId>('fridge');
  useEffect(()=>{const restored=restore(location.search,localStorage.getItem('sloy52-config'));setConfig({...restored,zones:normalizeZones(restored,restored.zones)});setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem('sloy52-config',JSON.stringify(config))},[config,ready]);
  const errors=validateDimensions(config),result=useMemo(()=>calculate(config),[config]);
  const selectedOptions=selectedOptionLabels(config.options),walls=availableWalls(config),activeWallSafe=walls.some(wall=>wall.id===activeWall)?activeWall:walls[0].id;
  const setLayout=(layout:Layout)=>setConfig(current=>{const next={...current,layout,dimensions:{...current.dimensions,b:current.dimensions.b||2400,c:current.dimensions.c||2200,islandLength:current.dimensions.islandLength||1800},options:current.options.filter(option=>option!=='island'||layout==='island')};return {...next,zones:normalizeZones(next,defaultZones(layout))}});
  const updateDimension=(id:keyof KitchenConfig['dimensions'],value:number)=>setConfig(current=>{const next={...current,dimensions:{...current.dimensions,[id]:value}};return {...next,zones:normalizeZones(next,next.zones)}});
  const updateZone=(zone:ZoneId,wall:WallId,module:number)=>setConfig(current=>{const next={...current,zones:{...current.zones,[zone]:{wall,module}}};return {...next,zones:normalizeZones(next,next.zones)}});
  const toggle=(id:OptionId)=>setConfig(current=>({...current,options:current.options.includes(id)?current.options.filter(option=>option!==id):[...current.options,id]}));
  async function copy(){const url=`${location.origin}/calculator?${serialize(config)}`;try{await navigator.clipboard.writeText(url);setMessage('Ссылка на конфигурацию скопирована')}catch{setMessage('Не удалось скопировать ссылку автоматически')}}
  if(!ready)return <div className="loading">Загружаем конфигурацию…</div>;
  return <div className="configurator">
    <aside className="configPreview"><p className="eyebrow">Единая модель кухни</p><div className="configViewTabs" role="tablist" aria-label="Проекции конфигурации"><button type="button" role="tab" aria-selected={view==='plan'} onClick={()=>setView('plan')}>План сверху</button><button type="button" role="tab" aria-selected={view==='front'} onClick={()=>setView('front')}>Развёртки стен</button></div>{view==='front'&&<WallNavigator walls={walls} active={activeWallSafe} set={setActiveWall}/>} {view==='plan'?<KitchenDiagram config={config} large selectedZone={step===2?selectedZone:undefined} onPlaceZone={step===2?(wall,module)=>updateZone(selectedZone,wall,module):undefined}/>:<KitchenFront config={config} wallId={activeWallSafe} selectedZone={step===2?selectedZone:undefined} onPlaceZone={step===2?(wall,module)=>updateZone(selectedZone,wall,module):undefined}/>}<div className="printProjections"><KitchenDiagram config={config}/>{walls.map(wall=><KitchenFront key={wall.id} config={config} wallId={wall.id}/>)}</div><p>{step===2?`Выбрано: ${zones.find(zone=>zone.id===selectedZone)?.name}. Нажмите на свободный модуль на любой из двух схем.`:view==='plan'?'Размеры задают число условных модулей; значки показывают холодильник, мойку и варочную поверхность.':'Развёртка использует те же модули и те же зоны, что и план сверху.'}</p><div className="serviceChips">{config.options.filter(option=>option==='delivery'||option==='installation').map(option=><span key={option}>{option==='delivery'?'Доставка':'Монтаж'}</span>)}</div></aside>
    <section className="configPanel"><ol className="steps" aria-label="Шаги конфигуратора">{steps.map((label,index)=>{const number=index+1;return <li key={label} className={number===step?'active':number<step?'done':''}><button type="button" onClick={()=>setStep(number)} aria-current={number===step?'step':undefined}><span>{number}</span><small>{label}</small></button></li>})}</ol>
      {step===1&&<section className="stepPane"><p className="eyebrow">Шаг 1 из 5</p><h1>Форма и размеры</h1><div className="layoutChoices">{layouts.map(layout=><button key={layout.id} type="button" aria-pressed={config.layout===layout.id} onClick={()=>setLayout(layout.id)}><LayoutIcon type={layout.id}/><span>{layout.name}</span></button>)}</div><div className="dimensions"><Dimension id="a" label="Стена A" value={config.dimensions.a} error={errors.a} set={value=>updateDimension('a',value)}/>{config.layout!=='straight'&&<Dimension id="b" label="Стена B" value={config.dimensions.b||0} error={errors.b} set={value=>updateDimension('b',value)}/>} {config.layout==='u'&&<Dimension id="c" label="Стена C" value={config.dimensions.c||0} error={errors.c} set={value=>updateDimension('c',value)}/>} {config.layout==='island'&&<Dimension id="islandLength" label="Длина острова" value={config.dimensions.islandLength||0} error={errors.islandLength} set={value=>updateDimension('islandLength',value)}/>}</div><p className="notice">Количество условных модулей пересчитывается от длины стены с шагом около 600 мм. Это демонстрационная схема, не производственный чертёж.</p></section>}
      {step===2&&<section className="stepPane"><p className="eyebrow">Шаг 2 из 5</p><h1>Расположение зон</h1><p className="stepHint">Сначала выберите элемент, затем нажмите на свободный модуль на плане. Это же работает с клавиатуры: Tab → Enter.</p><div className="zonePicker" role="radiogroup" aria-label="Выберите зону для размещения">{zones.map(zone=>{const place=config.zones[zone.id];return <button type="button" key={zone.id} role="radio" aria-checked={selectedZone===zone.id} className={selectedZone===zone.id?'selected':''} onClick={()=>setSelectedZone(zone.id)}><ZoneGlyph zone={zone.id}/><span><b>{zone.name}</b><small>Сейчас: {place.wall.toUpperCase()} · модуль {place.module+1}</small></span></button>})}</div><p className="notice">Расположение зон меняет план и развёртки, но не используется как отдельный ценовой коэффициент.</p></section>}
      {step===3&&<section className="stepPane"><p className="eyebrow">Шаг 3 из 5</p><h1>Материалы</h1><h2>Фасад</h2><div className="materialChoices">{facades.map(material=><button type="button" key={material.id} aria-pressed={config.facade===material.id} onClick={()=>setConfig(current=>({...current,facade:material.id as FacadeId}))}><i className={`texture ${material.texture}`}/><b>{material.name}</b><small>{material.note}</small></button>)}</div><h2>Столешница</h2><div className="materialChoices">{countertops.map(material=><button type="button" key={material.id} aria-pressed={config.top===material.id} onClick={()=>setConfig(current=>({...current,top:material.id as TopId}))}><i className={`texture ${material.texture}`}/><b>{material.name}</b><small>{material.note}</small></button>)}</div><h2>Ручка</h2><div className="handleChoices">{handles.map(handle=><button type="button" key={handle.id} aria-pressed={config.handle===handle.id} onClick={()=>setConfig(current=>({...current,handle:handle.id as KitchenConfig['handle']}))}><i className={`handleSwatch ${handle.id}`}/><b>{handle.name}</b><small>{handle.note}</small></button>)}</div></section>}
      {step===4&&<section className="stepPane"><p className="eyebrow">Шаг 4 из 5</p><h1>Оснащение</h1><p className="stepHint">Оснащение меняет фронтальные схемы; услуги показаны рядом с проекцией и не рисуются внутри кухни.</p><div className="options">{optionList.map(option=>{const disabled=option.id==='island'&&config.layout!=='island',selected=config.options.includes(option.id);return <label key={option.id} className={`${disabled?'disabled ':''}${selected?'selected':''}`}><input type="checkbox" checked={selected} disabled={disabled} onChange={()=>toggle(option.id)}/><span><b>{option.name}</b><small>{disabled?'Доступно только для планировки с островом.':option.note}</small></span>{selected&&<em aria-hidden="true">✓</em>}</label>})}</div></section>}
      {step===5&&<section className="stepPane result"><p className="eyebrow">Шаг 5 из 5</p><h1>Черновик расчёта</h1><dl><div><dt>Планировка и размеры</dt><dd>{layouts.find(layout=>layout.id===config.layout)?.name}, {dimensionSummary(config)}</dd></div><div><dt>Зоны</dt><dd>{zones.map(zone=>`${zone.name}: ${config.zones[zone.id].wall.toUpperCase()}-${config.zones[zone.id].module+1}`).join(' · ')}</dd></div><div><dt>Материалы</dt><dd>{facades.find(item=>item.id===config.facade)?.name} · {countertops.find(item=>item.id===config.top)?.name} · {handles.find(item=>item.id===config.handle)?.name}</dd></div></dl><section className="selectedConfiguration"><p className="eyebrow">Оснащение и услуги</p>{selectedOptions.length?<ul>{selectedOptions.map(option=><li key={option}>{option}</li>)}</ul>:<p>Дополнительные позиции не выбраны.</p>}</section><section className="excludedConfiguration"><p className="eyebrow">Не входит</p><ul><li>Техника</li><li>Позиции, не указанные в черновике.</li></ul></section><div className="price"><span>Округлённый демонстрационный диапазон</span><strong>{money(result.low)} – {money(result.high)}</strong></div><p>На диапазон влияют длина, форма, фасад, столешница и выбранное оснащение. Расположение зон меняет черновик планировки, но не используется как отдельный ценовой коэффициент.</p><div className="resultActions"><button type="button" className="button secondary" onClick={()=>setStep(1)}>Изменить параметры</button><button type="button" className="button secondary" onClick={()=>window.print()}>Распечатать расчёт</button><button type="button" className="button secondary" onClick={copy}>Скопировать ссылку</button><Link className="button" href={`/contacts?${serialize(config)}`}>Обсудить расчёт</Link></div><p className="status" aria-live="polite">{message}</p></section>}
      <div className="stepNav">{step>1&&<button type="button" className="textButton" onClick={()=>setStep(current=>current-1)}>Назад</button>}{step<5&&<button type="button" className="button" disabled={step===1&&Object.keys(errors).length>0} onClick={()=>setStep(current=>current+1)}>Продолжить</button>}</div>
    </section>
  </div>;
}
function money(value:number){return value>=1_000_000?`${(value/1_000_000).toFixed(1).replace('.',',')} млн ₽`:`${Math.round(value/10_000)*10} тыс. ₽`}
function WallNavigator({walls,active,set}:{walls:{id:WallId;label:string;modules:number}[];active:WallId;set:(wall:WallId)=>void}){const index=Math.max(0,walls.findIndex(wall=>wall.id===active)),previous=walls[(index-1+walls.length)%walls.length],next=walls[(index+1)%walls.length];return <div className="wallNavigator" aria-label="Переключение развёрток стен"><button type="button" className="wallArrow" aria-label={`Показать предыдущую: ${previous.label}`} onClick={()=>set(previous.id)}>←</button><div><b>{walls[index].label}</b><small>Нажимайте стрелки, чтобы переключать стены</small></div><button type="button" className="wallArrow" aria-label={`Показать следующую: ${next.label}`} onClick={()=>set(next.id)}>→</button></div>}
function ZoneGlyph({zone}:{zone:ZoneId}){return <span className={`zoneGlyph ${zone}`} aria-hidden="true">{zone==='fridge'?'▯':zone==='sink'?'⌒':'◌'}</span>}
function Dimension({id,label,value,error,set}:{id:string;label:string;value:number;error?:string;set:(value:number)=>void}){return <label htmlFor={id}>{label}<span className="inputUnit"><input id={id} type="number" value={Number.isNaN(value)?'':value} onChange={event=>set(event.target.valueAsNumber)} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/><span>мм</span></span>{error&&<small className="error" id={`${id}-error`}>{error}</small>}</label>}
function LayoutIcon({type}:{type:Layout}){return <svg viewBox="0 0 72 48" aria-hidden="true"><path d="M8 8h56v10H8z"/>{type!=='straight'&&<path d="M8 18h10v24H8z"/>}{type==='u'&&<path d="M54 18h10v24H54z"/>}{type==='island'&&<path d="M26 32h28v9H26z"/>}</svg>}
