'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {calculate,defaults,dimensionSummary,KitchenConfig,Layout,OptionId,restore,serialize,validateDimensions} from '@/lib/configurator';
import {facades,countertops,FacadeId,TopId} from '@/data/materials';
import {KitchenDiagram} from './KitchenDiagram';

const layouts:{id:Layout;name:string}[]=[{id:'straight',name:'Прямая'},{id:'corner',name:'Угловая'},{id:'u',name:'П-образная'},{id:'island',name:'С островом'}];
const optionList:{id:OptionId;name:string;note?:string}[]=[{id:'uppers',name:'Верхние шкафы'},{id:'columns',name:'Колонны под технику'},{id:'island',name:'Остров',note:'Только для планировки с островом'},{id:'lights',name:'Подсветка'},{id:'drawers',name:'Организация ящиков'},{id:'delivery',name:'Доставка'},{id:'installation',name:'Монтаж'}];

export function Configurator(){
  const [ready,setReady]=useState(false),[step,setStep]=useState(1),[config,setConfig]=useState<KitchenConfig>(defaults),[message,setMessage]=useState('');
  useEffect(()=>{setConfig(restore(location.search,localStorage.getItem('sloy52-config')));setReady(true)},[]);
  useEffect(()=>{if(ready)localStorage.setItem('sloy52-config',JSON.stringify(config))},[config,ready]);
  const errors=validateDimensions(config),result=useMemo(()=>calculate(config),[config]);
  const setLayout=(layout:Layout)=>setConfig(c=>({...c,layout,dimensions:{...c.dimensions,b:c.dimensions.b||2400,c:c.dimensions.c||2200,islandLength:c.dimensions.islandLength||1800},options:c.options.filter(o=>o!=='island'||layout==='island')}));
  const toggle=(id:OptionId)=>setConfig(c=>({...c,options:c.options.includes(id)?c.options.filter(o=>o!==id):[...c.options,id]}));
  async function copy(){const url=`${location.origin}/calculator?${serialize(config)}`;try{await navigator.clipboard.writeText(url);setMessage('Ссылка скопирована')}catch{const t=document.createElement('textarea');t.value=url;document.body.append(t);t.select();document.execCommand('copy');t.remove();setMessage('Ссылка скопирована запасным способом')}}
  if(!ready)return <div className="loading">Загружаем конфигурацию...</div>;
  return <div className="configurator">
    <aside className="configPreview"><p className="eyebrow">Схематичная компоновка</p><KitchenDiagram config={config} large/><p>Размеры стен и условные модули показаны прямо на плане. Терракотовый пунктир связывает рабочие зоны.</p></aside>
    <section className="configPanel">
      <ol className="steps" aria-label="Шаги конфигуратора">{[1,2,3,4].map(n=><li key={n} className={n===step?'active':n<step?'done':''}><button onClick={()=>setStep(n)} aria-current={n===step?'step':undefined}>{n}</button></li>)}</ol>
      {step===1&&<div className="stepPane"><p className="eyebrow">Шаг 1 из 4</p><h1>Планировка и размеры</h1><div className="layoutChoices">{layouts.map(l=><button key={l.id} aria-pressed={config.layout===l.id} onClick={()=>setLayout(l.id)}><LayoutIcon type={l.id}/><span>{l.name}</span></button>)}</div><div className="dimensions"><Dimension id="a" label="Основная сторона" value={config.dimensions.a} error={errors.a} set={v=>setConfig(c=>({...c,dimensions:{...c.dimensions,a:v}}))}/>{config.layout!=='straight'&&<Dimension id="b" label="Левая сторона" value={config.dimensions.b||0} error={errors.b} set={v=>setConfig(c=>({...c,dimensions:{...c.dimensions,b:v}}))}/>} {config.layout==='u'&&<Dimension id="c" label="Правая сторона" value={config.dimensions.c||0} error={errors.c} set={v=>setConfig(c=>({...c,dimensions:{...c.dimensions,c:v}}))}/>} {config.layout==='island'&&<Dimension id="islandLength" label="Длина острова" value={config.dimensions.islandLength||0} error={errors.islandLength} set={v=>setConfig(c=>({...c,dimensions:{...c.dimensions,islandLength:v}}))}/>}</div></div>}
      {step===2&&<div className="stepPane"><p className="eyebrow">Шаг 2 из 4</p><h1>Фасады и столешница</h1><h2>Фасад</h2><div className="materialChoices">{facades.map(m=><button key={m.id} aria-pressed={config.facade===m.id} onClick={()=>setConfig(c=>({...c,facade:m.id as FacadeId}))}><i className={`texture ${m.texture}`}/><b>{m.name}</b><small>{m.note}</small></button>)}</div><h2>Столешница</h2><div className="materialChoices">{countertops.map(m=><button key={m.id} aria-pressed={config.top===m.id} onClick={()=>setConfig(c=>({...c,top:m.id as TopId}))}><i className={`texture ${m.texture}`}/><b>{m.name}</b><small>{m.note}</small></button>)}</div></div>}
      {step===3&&<div className="stepPane"><p className="eyebrow">Шаг 3 из 4</p><h1>Комплектация</h1><div className="options">{optionList.map(o=>{const disabled=o.id==='island'&&config.layout!=='island';return <label key={o.id} className={disabled?'disabled':''}><input type="checkbox" checked={config.options.includes(o.id)} disabled={disabled} onChange={()=>toggle(o.id)}/><span><b>{o.name}</b>{disabled&&<small>{o.note}</small>}</span></label>})}</div><p className="notice">Техника не входит в демонстрационный расчёт.</p></div>}
      {step===4&&<div className="stepPane result"><p className="eyebrow">Шаг 4 из 4</p><h1>Черновик расчёта</h1><dl><div><dt>Планировка</dt><dd>{layouts.find(l=>l.id===config.layout)?.name}</dd></div><div><dt>Фасад</dt><dd>{facades.find(f=>f.id===config.facade)?.name}</dd></div><div><dt>Столешница</dt><dd>{countertops.find(t=>t.id===config.top)?.name}</dd></div><div><dt>Размеры</dt><dd>{dimensionSummary(config)}</dd></div></dl><div className="price"><span>Демонстрационный диапазон</span><strong>{money(result.low)} - {money(result.high)}</strong></div><p>На диапазон влияют общая длина, форма, фасады, столешница и выбранная комплектация. Расчёт не обещает цену до рубля. Он помогает понять порядок бюджета перед замером.</p><p className="notice">Демонстрационный расчёт. Значения не являются публичной офертой. Для реального проекта используются цены конкретного производства.</p><div className="resultActions"><button className="button secondary" onClick={()=>setStep(1)}>Изменить параметры</button><button className="button secondary" onClick={()=>window.print()}>Распечатать расчёт</button><button className="button secondary" onClick={copy}>Скопировать ссылку</button><Link className="button" href={`/contacts?${serialize(config)}`}>Обсудить расчёт</Link></div><p className="status" aria-live="polite">{message}</p></div>}
      <div className="stepNav">{step>1&&<button className="textButton" onClick={()=>setStep(s=>s-1)}>Назад</button>}{step<4&&<button className="button" disabled={step===1&&Object.keys(errors).length>0} onClick={()=>setStep(s=>s+1)}>Продолжить</button>}</div>
    </section>
  </div>
}

function money(v:number){return v>=1_000_000?`${(v/1_000_000).toFixed(1).replace('.',',')} млн ₽`:`${Math.round(v/10_000)*10} тыс. ₽`}
function Dimension({id,label,value,error,set}:{id:string;label:string;value:number;error?:string;set:(v:number)=>void}){return <label htmlFor={id}>{label}<span className="inputUnit"><input id={id} type="number" value={Number.isNaN(value)?'':value} onChange={e=>set(e.target.valueAsNumber)} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/><span>мм</span></span>{error&&<small className="error" id={`${id}-error`}>{error}</small>}</label>}
function LayoutIcon({type}:{type:Layout}){return <svg viewBox="0 0 72 48" aria-hidden="true"><path d="M8 8h56v10H8z"/>{type!=='straight'&&<path d="M8 18h10v24H8z"/>}{type==='u'&&<path d="M54 18h10v24H54z"/>}{type==='island'&&<path d="M26 32h28v9H26z"/>}</svg>}
