'use client';

import Link from 'next/link';
import {FormEvent,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {calculate,dimensionSummary,parse,selectedOptionLabels,serialize} from '@/lib/configurator';
import {facades,countertops,handles} from '@/data/materials';

const layoutNames={straight:'Прямая',corner:'Угловая',u:'П-образная',island:'С островом'} as const;
type ContactKind='Телефон'|'Telegram'|'Email';

export function DemoForm(){
  const [sent,setSent]=useState(false),[errors,setErrors]=useState<Record<string,string>>({}),[kind,setKind]=useState<ContactKind>('Телефон'),[submitted,setSubmitted]=useState<{name:string;contact:string}|null>(null);
  const params=useSearchParams();
  const config=useMemo(()=>parse(params.toString()),[params]);
  const result=config?calculate(config):null;
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),name=String(form.get('name')||'').trim(),contact=String(form.get('contact')||'').trim();const next:Record<string,string>={};if(!name)next.name='Укажите, как к вам обращаться.';if(!contact)next.contact=`Укажите ${kind.toLowerCase()}.`;if(Object.keys(next).length){setErrors(next);setSent(false);return;}setErrors({});setSubmitted({name,contact});event.currentTarget.reset();setSent(true)}
  const contactLabel=kind==='Email'?'Email':kind==='Telegram'?'Telegram':'Телефон';
  return <div><form className="contactForm" noValidate onSubmit={submit}>{config&&result&&<ConfigSummary config={config} low={result.low} high={result.high}/>} {!config&&<StartContext/>}<p className="notice">Демо-режим: данные не сохраняются и никуда не отправляются.</p><label>Имя<input name="name" required autoComplete="name" aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined} onInput={()=>setErrors(current=>({...current,name:''}))}/><small className="fieldHint">Достаточно имени или удобного обращения.</small>{errors.name&&<small className="fieldError" id="name-error">{errors.name}</small>}</label><label>Предпочтительный канал<select value={kind} onChange={event=>setKind(event.target.value as ContactKind)}><option>Телефон</option><option>Telegram</option><option>Email</option></select></label><label>{contactLabel}<input name="contact" required inputMode={kind==='Email'?'email':'text'} autoComplete={kind==='Email'?'email':'tel'} placeholder={kind==='Email'?'name@example.com':kind==='Telegram'?'@username':'Номер или удобный формат'} aria-invalid={!!errors.contact} aria-describedby={errors.contact?'contact-error':undefined} onInput={()=>setErrors(current=>({...current,contact:''}))}/><small className="fieldHint">Мы показываем только локальный сценарий — контакт не попадёт в URL или storage.</small>{errors.contact&&<small className="fieldError" id="contact-error">{errors.contact}</small>}</label><label>Комментарий <small>необязательно</small><textarea name="message" rows={5} placeholder="Что важно в комнате или в нынешнем хранении?"/></label><button className="button" type="submit">Показать, как отправится обращение</button>{sent&&submitted&&<section className="demoResult" aria-live="polite"><strong>Локальная демонстрация готова</strong><p>В реальном проекте были бы переданы: {submitted.name}, {kind.toLowerCase()} {submitted.contact}{config?', а также выбранная конфигурация кухни':''}. Здесь данные очищены и не отправлялись.</p></section>}</form><p className="contactNote">В рабочей версии на этом месте подключаются согласие, политика обработки данных и передача обращения в CRM.</p></div>;
}

function StartContext(){return <section className="contactSummary" aria-label="С чего можно начать"><p className="eyebrow">С чего можно начать</p><h2>Подготовьте только то, что уже есть</h2><ul className="summaryOptionList"><li>примерные размеры комнаты;</li><li>фото помещения или понравившийся концепт;</li><li>список техники и то, что не устраивает в хранении.</li></ul></section>}
function ConfigSummary({config,low,high}:{config:NonNullable<ReturnType<typeof parse>>;low:number;high:number}){const facade=facades.find(item=>item.id===config.facade)?.name,top=countertops.find(item=>item.id===config.top)?.name,handle=handles.find(item=>item.id===config.handle)?.name,options=selectedOptionLabels(config.options),zones=`Х: ${config.zones.fridge.wall.toUpperCase()}-${config.zones.fridge.module+1} · М: ${config.zones.sink.wall.toUpperCase()}-${config.zones.sink.module+1} · В: ${config.zones.cooktop.wall.toUpperCase()}-${config.zones.cooktop.module+1}`;return <section className="contactSummary" aria-label="Параметры из расчёта"><p className="eyebrow">Черновик из расчёта</p><h2>Параметры уже рядом</h2><dl><div><dt>Планировка</dt><dd>{layoutNames[config.layout]}</dd></div><div><dt>Размеры</dt><dd>{dimensionSummary(config)}</dd></div><div><dt>Зоны</dt><dd>{zones}</dd></div><div><dt>Фасад</dt><dd>{facade}</dd></div><div><dt>Столешница</dt><dd>{top}</dd></div><div><dt>Ручка</dt><dd>{handle}</dd></div><div><dt>Комплектация</dt><dd>{options.length?<ul className="summaryOptionList">{options.map(option=><li key={option}>{option}</li>)}</ul>:'без дополнительных позиций'}</dd></div><div><dt>Ориентир</dt><dd>{budgetRange(low,high)}</dd></div></dl><Link className="textButton" href={`/calculator?${paramsFor(config)}`}>Вернуться к расчёту</Link></section>}
function paramsFor(config:NonNullable<ReturnType<typeof parse>>){return serialize(config)}
function budgetRange(low:number,high:number){return `${formatBudget(low)}–${formatBudget(high)}`}function formatBudget(value:number){return value>=1_000_000?`${(value/1_000_000).toFixed(1).replace('.',',')}\u00a0млн\u00a0₽`:`${Math.round(value/1_000)}\u00a0тыс.\u00a0₽`}
