import type {KeyboardEvent} from 'react';
import type {KitchenConfig} from '@/lib/configurator';
import {buildKitchenModel,type WallId,type ZoneId} from '@/lib/kitchen-model';

const facadeFill={paint:'#aca99a','light-veneer':'#c5a87b','dark-veneer':'#594033',frame:'#d0c7b0'} as const;
const topFill={compact:'#343632',stone:'#d9d3c8',quartz:'#b9b1a7'} as const;
const zoneTitle:Record<ZoneId,string>={fridge:'Холодильник',sink:'Мойка',cooktop:'Варочная поверхность'};

export function KitchenFront({config,label='Схема стены кухни',wallId,selectedZone,onPlaceZone}:{config:KitchenConfig;label?:string;wallId?:WallId;selectedZone?:ZoneId;onPlaceZone?:(wall:WallId,module:number)=>void}){
  const model=buildKitchenModel(config),wall=model.walls.find(item=>item.id===wallId)||model.walls[0],upper=config.options.includes('uppers'),columns=config.options.includes('columns'),drawers=config.options.includes('drawers'),lights=config.options.includes('lights'),editable=!!selectedZone&&!!onPlaceZone;
  const facade=facadeFill[config.facade],top=topFill[config.top],frame=config.facade==='frame',displayModules=wall.id==='b'?[...wall.modules].reverse():wall.modules,unit=Math.min(112,570/wall.modules.length),start=(760-unit*wall.modules.length)/2;
  const tallIndexes=displayModules.map((module,index)=>module.kind==='tall'||(wall.id!=='island'&&columns&&index===0)?index:-1).filter(index=>index>=0);
  const counterSegments=segments(wall.modules.length,tallIndexes);
  return <svg className={`kitchenFront${editable?' kitchenFront--editable':''}`} viewBox="0 0 760 440" role="img" aria-label={`${label}: ${wall.label}.`} data-wall={wall.id} data-modules={wall.modules.length} data-lights={lights?'true':'false'} data-drawers={drawers?'true':'false'} data-uppers={upper?'true':'false'}>
    <defs><pattern id="elevation-grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#20211d" strokeOpacity=".055"/></pattern></defs><rect width="760" height="440" fill="#eee9df"/><rect x="44" y="34" width="672" height="350" fill="url(#elevation-grid)"/><path d="M55 378H705" stroke="#8a877e" strokeWidth="3"/>
    {displayModules.map((module,index)=>{const x=start+index*unit,fridge=module.kind==='tall',column=!fridge&&wall.id!=='island'&&columns&&index===0,tall=fridge||column,occupied=!!module.zone,place=()=>onPlaceZone?.(wall.id,module.index),key=(event:KeyboardEvent<SVGGElement>)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();place()}};return <g key={module.index} className={editable&&!occupied?'elevationModule elevationModule--available':'elevationModule'} role={editable&&!occupied?'button':undefined} tabIndex={editable&&!occupied?0:undefined} aria-label={editable&&!occupied?`Поставить ${zoneTitle[selectedZone!]}: ${wall.label}, модуль ${module.index+1}`:undefined} onClick={editable&&!occupied?place:undefined} onKeyDown={editable&&!occupied?key:undefined}>{tall?(fridge?<Fridge x={x} width={unit-4}/>:<TallColumn x={x} width={unit-4} fill={facade} frame={frame} handle={config.handle}/>):<><>{upper&&<Cabinet x={x} y={78} width={unit-4} height={104} fill={facade} frame={frame} handle={config.handle} upper/>}</><Cabinet x={x} y={274} width={unit-4} height={96} fill={facade} frame={frame} handle={config.handle} drawers={drawers}/>{module.zone&&<Appliance zone={module.zone} x={x} width={unit-4}/>}</>}</g>})}
    {counterSegments.map(([from,to])=>{const x=start+from*unit,width=(to-from)*unit-4;return <g key={`${from}-${to}`}><rect x={x-6} y="252" width={width+10} height={config.top==='compact'?14:config.top==='stone'?22:18} rx="1" fill={top}/><path d={`M${x-6} 267h${width+10}`} stroke="#242521" strokeOpacity=".52" strokeWidth="2"/></g>})}
    {upper&&lights&&counterSegments.map(([from,to])=>{const x=start+from*unit,width=(to-from)*unit-4;return <path key={`light-${from}`} d={`M${x} 194h${width}`} stroke="#e1b66c" strokeWidth="7" opacity=".95"/>})}<rect x={start-7} y="370" width={unit*wall.modules.length+7} height="10" fill="#4c4d46"/>
    <text x="380" y="414" textAnchor="middle" fontSize="13" fill="#20211d">{wall.label} · {wall.length} мм · {wall.modules.length} модулей</text><text x="380" y="433" textAnchor="middle" fontSize="10" fill="#5d5d56">Схема стены: холодильник — отдельный высокий модуль, без столешницы и верхнего шкафа</text>
  </svg>;
}
function segments(count:number,tall:number[]){const result:[number,number][]=[];let start=0;for(let index=0;index<=count;index++){if(index===count||tall.includes(index)){if(start<index)result.push([start,index]);start=index+1}}return result}
function Fridge({x,width}:{x:number;width:number}){const center=x+width/2;return <g aria-label="Холодильник"><rect x={x} y="70" width={width} height="300" fill="#d9d7cf" stroke="#20211d" strokeWidth="2"/><rect x={x+7} y="78" width={width-14} height="282" fill="#efede7" stroke="#6c6c66"/><path d={`M${x+7} 205h${width-14}M${x+width-17} 96v86m0 45v105`} stroke="#20211d" strokeWidth="2"/><text x={center} y="348" textAnchor="middle" fontSize="10" fill="#20211d">холодильник</text></g>}
function TallColumn({x,width,fill,frame,handle}:{x:number;width:number;fill:string;frame:boolean;handle:KitchenConfig['handle']}){const center=x+width/2;return <g aria-label="Высокая колонна"><Cabinet x={x} y={70} width={width} height={300} fill={fill} frame={frame} handle={handle}/><rect x={x+7} y="116" width={width-14} height="118" fill="#393a35" stroke="#20211d" strokeWidth="2"/><text x={center} y="348" textAnchor="middle" fontSize="10" fill="#20211d">колонна</text></g>}
function Appliance({zone,x,width}:{zone:ZoneId;x:number;width:number}){const cx=x+width/2;if(zone==='sink')return <g aria-label={zoneTitle[zone]}><rect x={x+5} y="214" width={Math.max(42,width-10)} height="34" rx="5" fill="#d6d4cc" stroke="#20211d" strokeWidth="2"/><ellipse cx={cx} cy="231" rx={Math.max(12,width/4)} ry="8" fill="none" stroke="#20211d" strokeWidth="2"/><circle cx={cx} cy="231" r="2" fill="#20211d"/><path d={`M${cx} 214v-18q0-14 15-14`} fill="none" stroke="#20211d" strokeWidth="3"/></g>;if(zone==='cooktop')return <g aria-label={zoneTitle[zone]}><rect x={x+4} y="207" width={Math.max(44,width-8)} height="42" rx="3" fill="#373833" stroke="#20211d" strokeWidth="2"/>{[-12,12].flatMap(dx=>[-9,9].map(dy=><circle key={`${dx}-${dy}`} cx={cx+dx} cy={228+dy} r="6" fill="none" stroke="#eee9df" strokeWidth="1.8"/>))}</g>;return null}
function Cabinet({x,y,width,height,fill,frame,handle,drawers=false,upper=false}:{x:number;y:number;width:number;height:number;fill:string;frame:boolean;handle:KitchenConfig['handle'];drawers?:boolean;upper?:boolean}){const rows=drawers?3:1;return <g><rect x={x} y={y} width={width} height={height} fill={fill} stroke="#20211d" strokeWidth="2"/>{frame&&<rect x={x+7} y={y+7} width={width-14} height={height-14} fill="none" stroke="#817865" strokeWidth="4"/>}{Array.from({length:rows-1},(_,i)=><path key={i} d={`M${x} ${y+height*(i+1)/rows}h${width}`} stroke="#20211d" strokeOpacity=".5"/>)}<Handle x={x} y={y} width={width} height={height} type={handle} rows={rows} upper={upper}/></g>}
function Handle({x,y,width,height,type,rows,upper}:{x:number;y:number;width:number;height:number;type:KitchenConfig['handle'];rows:number;upper:boolean}){return <g fill="none" stroke="#20211d" strokeWidth="3">{Array.from({length:rows},(_,index)=>{const center=y+height*(index+.5)/rows,edge=upper?y+height*(index+1)/rows-8:y+height*index/rows+8;if(type==='profile')return <path key={index} d={`M${x+7} ${edge}h${width-14}`} strokeWidth="4"/>;if(type==='bar')return <path key={index} d={`M${x+width/2-14} ${upper?center+2:center-11}v18m28-18v18m-28-9h28`}/>;return <circle key={index} cx={x+width-12} cy={upper?center+20:center} r="4" fill="#20211d"/>})}</g>}
