import {test,expect} from '@playwright/test';

const routes=['/','/projects','/projects/linen-light','/projects/walnut-line','/projects/chalk-frame','/projects/olive-island','/projects/ash-corner','/projects/graphite-block','/calculator','/materials','/about','/contacts','/missing-page'];
for(const route of routes)test(`прямой маршрут ${route}`,async({page})=>{await page.goto(route);await expect(page.locator('h1')).toHaveCount(1);await page.reload();await expect(page.locator('main')).toBeVisible()});

test('фильтр проектов сохраняется в URL',async({page})=>{await page.goto('/projects');await page.getByRole('button',{name:'Угловая'}).click();await expect(page).toHaveURL(/filter=corner/);await expect(page.locator('.projectCard')).toHaveCount(2)});

test('материалы ведут в расчёт с независимыми A/B и без крупного плана',async({page})=>{await page.goto('/materials');await expect(page.getByText('Сейчас редактируется вариант A.')).toBeVisible();await expect(page.getByRole('tab',{name:'Крупный план'})).toHaveCount(0);await page.getByRole('button',{name:/Тёмный шпон/}).click();await page.getByRole('button',{name:/Кварцевый агломерат/}).click();await page.getByRole('button',{name:/Скоба/}).click();await page.getByRole('tab',{name:'Вариант B'}).click();await expect(page.getByRole('button',{name:/Тёмный шпон/})).not.toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:/Матовая окраска/}).click();await page.getByRole('link',{name:'Использовать B в расчёте'}).click();await expect(page).toHaveURL(/facade=paint/);await expect(page).toHaveURL(/handle=bar/)});

test('пять шагов, зоны и проекции используют одну конфигурацию',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/calculator');await page.getByRole('button',{name:'Угловая'}).click();await page.getByRole('button',{name:'Продолжить'}).click();await expect(page.getByRole('heading',{name:'Расположение зон'})).toBeVisible();await page.locator('.zoneChoices select').nth(0).selectOption('b');await page.locator('.zoneChoices select').nth(1).selectOption('1');await page.getByRole('tab',{name:'План сверху'}).click();await expect(page.locator('.configPreview > .diagram')).toHaveAttribute('data-layout','corner');await page.getByRole('tab',{name:'Развёртки стен'}).click();await expect(page.getByRole('tab',{name:'Стена B'})).toBeVisible();await page.getByRole('tab',{name:'Стена B'}).click();await expect(page.locator('.configPreview > .kitchenFront')).toHaveAttribute('data-wall','b');await page.getByRole('button',{name:'Продолжить'}).click();await page.getByRole('button',{name:/Тёмный шпон/}).click();await page.getByRole('button',{name:'Продолжить'}).click();await page.getByText('Подсветка',{exact:true}).click();await page.getByText('Организация ящиков',{exact:true}).click();await page.getByRole('button',{name:'Продолжить'}).click();await expect(page.getByRole('heading',{name:'Черновик расчёта'})).toBeVisible();await page.getByRole('button',{name:'Скопировать ссылку'}).click();const link=await page.evaluate(()=>navigator.clipboard.readText());await expect(link).toContain('fridge=b%3A1');await page.goto(link);await expect(page.locator('.configPreview > .diagram')).toHaveAttribute('data-layout','corner')});

test('все формы строят корректные проекции',async({page})=>{for(const query of ['layout=straight&a=3000&facade=paint&top=compact&handle=profile','layout=corner&a=3000&b=2400&facade=frame&top=quartz&handle=bar','layout=u&a=3000&b=2400&c=2200&facade=dark-veneer&top=stone&handle=knob','layout=island&a=3000&islandLength=1800&facade=paint&top=compact&handle=profile']){await page.goto(`/calculator?${query}`);await expect(page.locator('.configPreview > .diagram')).toBeVisible();await page.getByRole('tab',{name:'Развёртки стен'}).click();await expect(page.locator('.configPreview > .kitchenFront')).toBeVisible()}});

test('оснащение меняет развёртку, а услуги остаются снаружи',async({page})=>{await page.goto('/calculator?layout=island&a=3000&islandLength=1800&facade=frame&top=quartz&handle=knob');await page.getByRole('button',{name:/Оснащение/}).click();await page.getByText('Верхние шкафы',{exact:true}).click();await page.getByText('Подсветка',{exact:true}).click();await page.getByText('Организация ящиков',{exact:true}).click();await page.getByText('Доставка',{exact:true}).click();await page.getByText('Монтаж',{exact:true}).click();await expect(page.locator('.serviceChips')).toContainText('Доставка');await expect(page.locator('.serviceChips')).toContainText('Монтаж');await page.getByRole('tab',{name:'Развёртки стен'}).click();await expect(page.locator('.configPreview > .kitchenFront')).toHaveAttribute('data-lights','true');await expect(page.locator('.configPreview > .kitchenFront')).toHaveAttribute('data-drawers','true')});

test('результат и контакты получают выбранную конфигурацию',async({page})=>{const query='layout=corner&a=3000&b=2400&facade=frame&top=quartz&handle=bar&options=uppers,lights,installation&fridge=a%3A0&sink=a%3A2&cooktop=b%3A1';await page.goto(`/calculator?${query}`);await page.getByRole('button',{name:/Черновик/}).click();const result=page.locator('.result');await expect(result.getByText('Верхние шкафы',{exact:true})).toBeVisible();await expect(result.getByText('Подсветка',{exact:true})).toBeVisible();await expect(result.getByText('Монтаж',{exact:true})).toBeVisible();await expect(result.getByText('Не входит',{exact:true})).toBeVisible();await page.getByRole('link',{name:'Обсудить расчёт'}).click();await expect(page.getByRole('heading',{name:'Параметры уже рядом'})).toBeVisible();await expect(page.getByText('Скоба',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Вернуться к расчёту'})).toHaveAttribute('href',/fridge=a%3A0/)});

test('форма контактов не отправляет персональные данные',async({page})=>{const posts:string[]=[];page.on('request',request=>{if(request.method()!=='GET')posts.push(request.url())});await page.goto('/contacts');await page.getByLabel('Имя').fill('Тест');await page.getByRole('textbox',{name:/Телефон/}).fill('почта');await page.getByRole('button',{name:'Показать, как отправится обращение'}).click();await expect(page.getByText(/данные очищены/)).toBeVisible();expect(posts).toEqual([])});

test('мобильное меню и вкладки доступны с клавиатуры',async({page,isMobile})=>{test.skip(!isMobile);await page.goto('/');const menu=page.getByRole('button',{name:'Меню'});await menu.click();await page.keyboard.press('Escape');await expect(menu).toBeFocused();await page.goto('/calculator');await page.getByRole('tab',{name:'Развёртки стен'}).click();await expect(page.getByRole('tab',{name:'Стена A'})).toBeVisible()});
