import {test,expect} from '@playwright/test';
const routes=['/','/projects','/projects/linen-light','/calculator','/materials','/about','/contacts'];
for(const route of routes)test(`прямой маршрут ${route}`,async({page})=>{await page.goto(route);await expect(page.locator('h1')).toHaveCount(1);await page.reload();await expect(page.locator('main')).toBeVisible()});
test('навигация и фильтр',async({page})=>{await page.goto('/');if(await page.getByRole('button',{name:'Меню'}).isVisible())await page.getByRole('button',{name:'Меню'}).click();await page.getByRole('link',{name:'Проекты',exact:true}).first().click();await page.getByRole('button',{name:'Угловая'}).click();await expect(page).toHaveURL(/filter=corner/);await expect(page.locator('.projectCard')).toHaveCount(2);await page.goBack();await expect(page).not.toHaveURL(/filter=corner/)});
test('конфигуратор, сохранение и ссылка',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/calculator');await page.getByRole('button',{name:'Угловая'}).click();await page.getByRole('button',{name:'Продолжить'}).click();await page.getByRole('button',{name:/Тёмный шпон/}).click();await page.getByRole('button',{name:'Продолжить'}).click();await page.getByText('Подсветка',{exact:true}).click();await page.getByRole('button',{name:'Продолжить'}).click();await expect(page.getByText('Демонстрационный диапазон')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Угловая'})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'4',exact:true}).click();await page.getByRole('button',{name:'Скопировать ссылку'}).click();await expect(page.getByText('Ссылка скопирована')).toBeVisible();const link=await page.evaluate(()=>navigator.clipboard.readText());await page.goto(link);await expect(page.getByRole('button',{name:'Угловая'})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'4',exact:true}).click();await expect(page.getByText('Черновик расчёта')).toBeVisible()});
test('форма не отправляет запрос',async({page})=>{const posts:string[]=[];page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});await page.goto('/contacts');await page.getByLabel('Имя').fill('Тест');await page.getByLabel('Способ связи').fill('почта');await page.getByRole('button',{name:'Показать демо-ответ'}).click();await expect(page.getByText(/данные очищены/)).toBeVisible();expect(posts).toEqual([])});
test('lightbox с клавиатуры',async({page})=>{await page.goto('/projects/linen-light');const opener=page.getByRole('button',{name:/Открыть галерею/});await expect(opener).toBeVisible();await opener.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByText('1 / 3')).toBeVisible();await page.keyboard.press('ArrowRight');await expect(page.getByText('2 / 3')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();await expect(opener).toBeFocused()});
test('мобильное меню',async({page,isMobile})=>{test.skip(!isMobile);await page.goto('/');const menu=page.getByRole('button',{name:'Меню'});await menu.click();const nav=page.getByRole('navigation',{name:'Основная навигация'});await expect(nav).toBeVisible();await page.keyboard.press('Escape');await expect(nav).not.toBeVisible();await expect(menu).toBeFocused();await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await nav.getByRole('link',{name:'Материалы'}).click();await expect(page).toHaveURL('/materials')});
test('контакты показывают переданный черновик',async({page})=>{await page.goto('/contacts?layout=corner&a=3000&b=2400&facade=frame&top=quartz&options=lights');await expect(page.getByRole('heading',{name:'Параметры уже рядом'})).toBeVisible();await expect(page.getByText('3000 × 2400 мм')).toBeVisible();await expect(page.getByText('Рамочный фасад')).toBeVisible()});
