import {dimensionRules,priceMatrix} from '@/data/pricing';
import type {FacadeId,TopId} from '@/data/materials';
export type Layout='straight'|'corner'|'u'|'island';
export type OptionId=keyof typeof priceMatrix.options;
export type KitchenConfig={layout:Layout;dimensions:{a:number;b?:number;c?:number;islandLength?:number};facade:FacadeId;top:TopId;options:OptionId[]};
export const optionLabels:Record<OptionId,string>={uppers:'Верхние шкафы',columns:'Колонны под технику',island:'Остров',lights:'Подсветка',drawers:'Организация ящиков',delivery:'Доставка',installation:'Монтаж'};
export function selectedOptionLabels(options:OptionId[]){return options.filter((option,index)=>options.indexOf(option)===index).map(option=>optionLabels[option]);}
export const defaults:KitchenConfig={layout:'straight',dimensions:{a:3000},facade:'paint',top:'compact',options:['uppers']};
const allowedLayouts:Layout[]=['straight','corner','u','island']; const facadeIds:FacadeId[]=['paint','light-veneer','dark-veneer','frame']; const topIds:TopId[]=['compact','stone','quartz']; const optionIds:OptionId[]=['uppers','columns','island','lights','drawers','delivery','installation'];
export function normalizeOptions(layout:Layout,opts:OptionId[]){return opts.filter((o,i)=>optionIds.includes(o)&&opts.indexOf(o)===i&&(o!=='island'||layout==='island'));}
export function validateDimensions(c:KitchenConfig){const errors:Record<string,string>={}; const required=['a',...(c.layout==='straight'?[]:['b']),...(c.layout==='u'?['c']:[]),...(c.layout==='island'?['islandLength']:[])] as (keyof KitchenConfig['dimensions'])[]; for(const key of required){const v=c.dimensions[key]; const r=dimensionRules[key]; if(typeof v!=='number'||!Number.isFinite(v)) errors[key]='Укажите размер'; else if(v<r.min||v>r.max) errors[key]=`Допустимо ${r.min}-${r.max} мм`; } return errors;}
export function totalLength(c:KitchenConfig){return (c.dimensions.a+(c.layout==='straight'?0:(c.dimensions.b||0))+(c.layout==='u'?(c.dimensions.c||0):0)+(c.layout==='island'?(c.dimensions.islandLength||0):0))/1000;}
export function dimensionSummary(c:KitchenConfig){const kitchen=[c.dimensions.a,...(c.layout==='straight'?[]:[c.dimensions.b]),...(c.layout==='u'?[c.dimensions.c]:[])].filter((v):v is number=>typeof v==='number'&&Number.isFinite(v));const base=`${kitchen.join(' × ')} мм`;return c.layout==='island'?`${base}, остров ${c.dimensions.islandLength} мм`:base;}
const round=(v:number)=>Math.ceil(v/priceMatrix.roundTo)*priceMatrix.roundTo;
export function calculate(c:KitchenConfig){const length=totalLength(c); const factor=priceMatrix.layout[c.layout]*priceMatrix.facade[c.facade]*priceMatrix.top[c.top]; const extras=normalizeOptions(c.layout,c.options).reduce((s,o)=>s+priceMatrix.options[o],0); return {low:round(length*priceMatrix.basePerMeter[0]*factor+extras),high:round(length*priceMatrix.basePerMeter[1]*factor+extras*1.12)};}
export function serialize(c:KitchenConfig){const p=new URLSearchParams();p.set('layout',c.layout);p.set('a',String(c.dimensions.a));if(c.layout!=='straight'&&c.dimensions.b)p.set('b',String(c.dimensions.b));if(c.layout==='u'&&c.dimensions.c)p.set('c',String(c.dimensions.c));if(c.layout==='island'&&c.dimensions.islandLength)p.set('islandLength',String(c.dimensions.islandLength));p.set('facade',c.facade);p.set('top',c.top);if(c.options.length)p.set('options',c.options.join(','));return p.toString();}
export function parse(raw:string):KitchenConfig|null{try{const p=new URLSearchParams(raw);if(!p.has('layout'))return null;const layout=p.get('layout') as Layout;if(!allowedLayouts.includes(layout))return null;const c:KitchenConfig={layout,dimensions:{a:Number(p.get('a'))},facade:p.get('facade') as FacadeId,top:p.get('top') as TopId,options:(p.get('options')||'').split(',').filter(Boolean) as OptionId[]};if(!facadeIds.includes(c.facade)||!topIds.includes(c.top))return null;for(const k of ['b','c','islandLength'] as const)if(p.has(k))c.dimensions[k]=Number(p.get(k));c.options=normalizeOptions(layout,c.options);return Object.keys(validateDimensions(c)).length?null:c;}catch{return null}}
export function restore(url:string,stored:string|null){const fromUrl=parse(url);if(fromUrl)return fromUrl;if(stored)try{const raw=JSON.parse(stored);return parse(serialize(raw))||defaults}catch{}return defaults;}
